package com.blinktrade.api;

public enum SystemEventType
{
    CLOSED,
    ERROR,
    OPENED,

    RAW_MESSAGE,
    SENT_RAW_MESSAGE,
    ERROR_MESSAGE,

    LOGIN_OK,
    LOGIN_ERROR,
    CHANGE_PASSWORD_RESPONSE,

    NEWS,

    // Passwords
    TWO_FACTOR_SECRET,
    PASSWORD_CHANGED_OK,
    PASSWORD_CHANGED_ERROR,

    // Profile
    UPDATE_PROFILE_RESPONSE,
    PROFILE_REFRESH,

    // Deposits
    DEPOSIT_METHODS_RESPONSE,
    DEPOSIT_RESPONSE,
    DEPOSIT_REFRESH,
    PROCESS_DEPOSIT_RESPONSE,
    DEPOSIT_LIST_RESPONSE,

    // Withdraws
    WITHDRAW_RESPONSE,
    WITHDRAW_CONFIRMATION_RESPONSE,
    WITHDRAW_LIST_RESPONSE,
    WITHDRAW_REFRESH,
    PROCESS_WITHDRAW_RESPONSE,

    // Positions & balance
    POSITION_RESPONSE,
    BALANCE_RESPONSE,

    // Trading
    ORDER_LIST_RESPONSE,
    HEARTBEAT,
    EXECUTION_REPORT,

    // Securities
    SECURITY_LIST,
    SECURITY_STATUS,

    // Trade History
    TRADE_HISTORY,
    TRADE_HISTORY_RESPONSE,

    TRADERS_RANK_RESPONSE,
    LEDGER_LIST_RESPONSE,

    // API Key
    API_KEY_LIST_RESPONSE,
    API_KEY_REVOKE_RESPONSE,
    API_KEY_CREATE_RESPONSE,

    /* Card */
    CARD_LIST_RESPONSE,
    CARD_DISABLE_RESPONSE,
    CARD_CREATE_RESPONSE,

    // Brokers
    BROKER_LIST_RESPONSE,
    CUSTOMER_LIST_RESPONSE,
    CUSTOMER_DETAIL_RESPONSE,
    VERIFY_CUSTOMER_RESPONSE,
    VERIFY_CUSTOMER_UPDATE,

    // Market Data
    MARKET_DATA_FULL_REFRESH,
    MARKET_DATA_INCREMENTAL_REFRESH,
    MARKET_DATA_REQUEST_REJECT,

    LINE_OF_CREDIT_LIST_RESPONSE,
    GET_LINE_OF_CREDIT_RESPONSE,
    PAY_LINE_OF_CREDIT_RESPONSE,

    TRADING_SESSION_STATUS,
    TRADE,
    TRADE_CLEAR,
    ORDER_BOOK_CLEAR,
    ORDER_BOOK_DELETE_ORDERS_THRU,
    ORDER_BOOK_DELETE_ORDER,
    ORDER_BOOK_NEW_ORDER,
    ORDER_BOOK_UPDATE_ORDER
}